site_name: TreatJS
site_description: TreatJS Documentation.

repo_name: GitHub
repo_url: https://github.com/keil/TreatJS

site_author: Matthias Keil

copyright: Copyright &copy; 2015, <a href="http://proglang.informatik.uni-freiburg.de/treatjs/">Proglang, University of Freiburg</a>.

pages:
- ['index.md', 'Home']
- ['introduction.md', 'Introduction']
- ['requirements.md', 'Requirements']
- ['installation.md', 'Installation']
- ['configuration.md', 'Configuration']
- ['contracts/base.md', 'Contracts', 'Base']
- ['contracts/function.md', 'Contracts', 'Function']
- ['license.md', 'License']
